services:
  - type: web
    name: nyumba-salama-fastapi
    runtime: python
    repo: https://github.com/sankhathecoder7-cyber/nyumba-salama-backend
    plan: free
    branch: main

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: JWT_SECRET
        value: nyumbasalama-super-secret-key-change-in-production

      - key: GROQ_API_KEY
        value: your_groq_api_key