services:
  - type: web
    name: nyumba-salama-fastapi
    runtime: python
    repo: https://github.com/sankhathecoder7-cyber/nyumba-salama-backend
    plan: free
    branch: main

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:

      - key: PYTHON_VERSION
        value: 3.11.9

      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./pydev.db

      - key: JWT_SECRET
        value: nyumbasalama-super-secret-key-change-in-production

      - key: GROQ_API_KEY
        sync: false

      - key: GROQ_BASE_URL
        value: https://api.groq.com/openai/v1

      - key: CHAT_MODEL
        value: llama-3.3-70b-versatile

      - key: TEMPERATURE
        value: 0.3

      - key: MAX_TOKENS
        value: 1000